name: "Database Clear and Restore Serverless Deploy"

on: 
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install node dependencies
        run: |
          npm install
          npm install -g serverless@2.1.0
        working-directory: ./database-clear          
      - name: Serverless deploy 
        run: |
          serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}
        working-directory: ./database-clear 

